name: Docker Build
on:
  push:
    branches: [master]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Create GITHUB_SHA_SHORT
        id: meta
        run: |
          echo "github_sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/bake-action@v6
        with:
          source: .
          push: true
          set: |
            go.tags=ghcr.io/kahnwong/docker-bake-playground/go:${{ steps.meta.outputs.github_sha_short }}
            rust.tags=ghcr.io/kahnwong/docker-bake-playground/rust:${{ steps.meta.outputs.github_sha_short }}
